### PR TITLE
Fix users in brain when user doesn't have a profile

### LINKED ISSUE #388: TypeError: Cannot read property 'email' of undefined
* [ X ] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [ X ] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [ X ] I've searched for any related issues and avoided creating a duplicate issue.

TypeError: Cannot read property 'email' of undefined
At line 220 https://github.com/slackapi/hubot-slack/blob/master/src/bot.coffee#L220
Full backtrace:
[Wed Jan 04 2017 18:04:59 GMT+0000 (UTC)] ERROR TypeError: Cannot read property 'email' of undefined
  at SlackBot.userChange (/usr/src/bot/node_modules/hubot-slack/src/bot.coffee:220:7, <js>:285:36)
  at RTMClient.<anonymous> (/usr/src/bot/node_modules/hubot-slack/src/bot.coffee:1:1, <js>:3:61)
  at RTMClient.emit (/usr/src/bot/node_modules/eventemitter3/index.js:116:35)
  at RTMClient.emit (/usr/src/bot/node_modules/@slack/client/lib/clients/client.js:79:39)
  at RTMClient._handleWsMessageViaEventHandler (/usr/src/bot/node_modules/@slack/client/lib/clients/rtm/client.js:465:10)
  at RTMClient.handleWsMessage (/usr/src/bot/node_modules/@slack/client/lib/clients/rtm/client.js:419:10)
  at WebSocket.wrapper (/usr/src/bot/node_modules/@slack/client/node_modules/lodash/lodash.js:4968:19)
  at emitTwo (events.js:87:13)
  at WebSocket.emit (events.js:172:7)
  at Receiver.ontext (/usr/src/bot/node_modules/ws/lib/WebSocket.js:841:10)
  at /usr/src/bot/node_modules/ws/lib/Receiver.js:536:18
  at Receiver.applyExtensions (/usr/src/bot/node_modules/ws/lib/Receiver.js:371:5)
  at /usr/src/bot/node_modules/ws/lib/Receiver.js:508:14
  at Receiver.flush (/usr/src/bot/node_modules/ws/lib/Receiver.js:347:3)
  at Receiver.opcodes.1.finish (/usr/src/bot/node_modules/ws/lib/Receiver.js:541:12)
  at Receiver.expectHandler (/usr/src/bot/node_modules/ws/lib/Receiver.js:499:31)
  at Receiver.add (/usr/src/bot/node_modules/ws/lib/Receiver.js:103:24)
  at TLSSocket.realHandler (/usr/src/bot/node_modules/ws/lib/WebSocket.js:825:20)
  at emitOne (events.js:77:13)
  at TLSSocket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at TLSSocket.Readable.push (_stream_readable.js:110:10)
  at TLSWrap.onread (net.js:523:20)

#### Reproducible in:
{project_name} version:
OS version(s): Ubuntu
Device(s):

#### Steps to reproduce:

N/A
### Expected result:
N/A

### Actual result:
N/A

### Attachments:
N/A

### PR DESCRIPTION
**Pull request by aoberoi**
* [x] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [x] I've been mindful about doing atomic commits, adding documentation to my changes, not refactoring too much.
* [x] I've a descriptive title and added any useful information for the reviewer. Where appropriate, I've attached a screenshot and/or screencast (gif preferrably).
* [x] I've written tests to cover the new code and functionality included in this PR.
* [x] I've read, agree to, and signed the [Contributor License Agreement (CLA)](https://docs.google.com/a/slack-corp.com/forms/d/1q_w8rlJG_x_xJOoSUMNl7R35rkpA7N6pUkKhfHHMD9c/viewform).

### CODE REVIEW

File: src/bot.coffee [hunk 1]
```diff
@@ -217,8 +217,8 @@ class SlackBot extends Adapter
       id: user.id
       name: user.name
       real_name: user.real_name
-      email_address: user.profile.email
       slack: {}
+    newUser.email_address = user.profile.email unless not user.profile
```
Comment (Roach) [inline src/bot.coffee]: `unless not`

fillion
