### PR TITLE
Tidying up

### LINKED ISSUE #384: add hubot to peerDependencies
* [x] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Reproducible in:
hubot-slack version: 4.2.2
OS version(s): all
Device(s): all

#### Steps to reproduce:

NA

### LINKED ISSUE #386: audit and clean up logger usage
* [x] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Reproducible in:
{project_name} version: all
OS version(s): all
Device(s): all

#### Steps to reproduce:

NA

### LINKED ISSUE #412: update engines for a higher minimum node version
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://github.com/slackapi/hubot-slack/blob/master/CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

this package is no longer compatible with node 0.10. the most obvious reason is that one of its dependencies (`@slack/client`) requires 0.12 at a minimum.

#### Reproducible in:
hubot-slack version: 4.3.3

#### Steps to reproduce:

See #411

### Expected result:

See #411

### Actual result:

See #411

### LINKED ISSUE #444: Update node versions in Travis
### Description

for v4.x, node versions 0.10.x to current are all supported, so they should be added to the Travis matrix.

note: codecov's node uploader does not support 0.10.x, but for now does support 0.12.x but probably not for long. we are at risk of not getting coverage information at all if we don't start testing on later versions of node.

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### PR DESCRIPTION
**Pull request by aoberoi**
###  Summary

This is meant to be purely cosmetic. Removed old and unuseful comments, made all strings use the same quotes, used some more idiomatic syntax for coffeescript.

There's one functional change, which is a bug fix here: https://github.com/slackapi/hubot-slack/compare/master...aoberoi:tidying-up?expand=1#diff-d058f94b15d7abb97d499186d40867ffR276

I've tested this by running all the documentation examples in #478 

fixes #386 
fixes #444 
fixes #412 
fixes #384 

### Requirements (place an `x` in each `[ ]`)

* [ ] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [ ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).

### CODE REVIEW

File: src/bot.coffee [hunk 1]
```diff
@@ -102,149 +121,187 @@ class SlackBot extends Adapter
...
     # The returned user from a message or reaction event is guaranteed to contain:
-    # 
+    #
     # id {String}:              Slack user ID
     # slack.is_bot {Boolean}:   Flag indicating whether user is a bot
     # name {String}:            Slack username
     # real_name {String}:       Name of Slack user or bot
     # room {String}:            Slack channel ID for event (will be empty string if no channel in event)
     ###
+    # NOTE: should this be using `updateUserInBrain()`?
```
Comment (aoberoi) [inline src/bot.coffee]: @shanedewael while this PR is about tidying up, not changing the implementation, i wanted to point this out because i felt like it may become a source of bugs. `updateUserInBrain()` does quite a bit of processing to make sure the "shape" of the user stored in the brain fits a specific hubot-compatible shape. if we skip that work here, are we going to break things? can we just call that function here (since it essentially does the same thing)?

File: src/message.coffee [hunk 2]
```diff
@@ -128,68 +153,93 @@ class SlackTextMessage extends TextMessage
...
-    )
-    .catch((error) =>
-      client.robot.logger.error "Error getting user info #{id}: #{error.message}"
-      return "<@#{id}>"
-    )
+    client.web.users.info(id)
+      .then (res) =>
+        if res?.user?
+          user = res.user
+          mention = new SlackMention(user.id, "user", user)
```
Comment (shanedewael) [inline src/message.coffee]: To match styling in `replaceLinks()`, might want to change to `mentions.push new SlackMention(user.id, "user", user)`

File: src/message.coffee [hunk 3]
```diff
@@ -128,68 +153,93 @@ class SlackTextMessage extends TextMessage
...
-      client.robot.logger.error "Error getting conversation info #{id}: #{error.message}"
-      return "<\##{id}>"
-    )
-
+    client.web.conversations.info(id)
+      .then (res) =>
+        if res?.channel?
+          conversation = res.channel
+          mention = new SlackMention(conversation.id, 'conversation', conversation)
+          mentions.push(mention)
```
Comment (shanedewael) [inline src/message.coffee]: same as above

File: test/stubs.coffee [hunk 4]
```diff
@@ -151,6 +152,7 @@ beforeEach ->
   @stubs.chatMock =
     postMessage: (msg, room, opts) =>
       @stubs.send(msg, room, opts)
+      Promise.resolve()
   @stubs.conversationsMock =
     setTopic: (id, topic) =>
```
Comment (shanedewael) [inline test/stubs.coffee]: does this stubbed method need a `Promise.resolve()`?

Comment (aoberoi) [reply test/stubs.coffee]: yeah it was failing a test without it because there's some code that uses .catch() on the result of this method.

Comment (aoberoi) [reply test/stubs.coffee]: and unlike `SlackBot#send()`, this actually does have an declared return type, so we'd want the stub to have the same.
